### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by Tecko71** [RussellValiant/TVRemote#1]
I would like to see that we can choose between artist art or album art. No switching all the time.  Also I like to see the option lyrics added.  Now I have to use web display for this feature . 
I use Roon rock and I use apple TV as a display

**Comment by RussellValiant** [comment]
There’s an options it disable background animations in ATV > Settings > Apps > TV:Remote. This will stop the background image from changing.
Lyrics aren’t featured in the Roon API.
